name: notify-amount-transferred / test

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/notify-amount-transferred--test.yaml
      - notify-amount-transferred/**
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/notify-amount-transferred--test.yaml
      - notify-amount-transferred/**

defaults:
  run:
    working-directory: notify-amount-transferred

jobs:
  lint:
    needs: fix
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: aquaproj/aqua-installer@v1.1.2
        with:
          aqua_version: v1.24.0
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: github-comment exec -- yarn install --frozen-lockfile
      - run: github-comment exec -- yarn lint

  fix:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          # update the pull request branch
          ref: ${{ github.head_ref }}
          token:  ${{ secrets.GHA_TOKEN }}
      - uses: aquaproj/aqua-installer@v1.1.2
        with:
          aqua_version: v1.24.0
      - run: github-comment exec -- yarn install --frozen-lockfile
      - run: github-comment exec -- yarn fix
      - uses: int128/update-generated-files-action@v2

  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: aquaproj/aqua-installer@v1.1.2
        with:
          aqua_version: v1.24.0
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: github-comment exec -- yarn install --frozen-lockfile
      - run: github-comment exec -- yarn test