name: notify-common-expense / deploy

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/notify-common-expense--deploy.yaml
      - notify-common-expense/**

defaults:
  run:
    working-directory: notify-common-expense

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "22"
      - run: npm ci
      - name: Generate .clasp.json
        run: |
          echo "{\"scriptId\":\"${{ secrets.NOTIFY_COMMON_EXPENSE_SCRIPT_ID }}\",\"rootDir\":\"dist\"}" > .clasp.json
      - run: |
          mkdir -p "${HOME}"
          echo '${{ secrets.CLASPRC_JSON }}' > "${HOME}/.clasprc.json"
      - run: npm run deploy:prod
